function (add_demo DEMO_NAME)
    file (GLOB_RECURSE HDRS "${DEMO_NAME}/*.h" "${DEMO_NAME}/*.hpp")
    file (GLOB_RECURSE SRCS "${DEMO_NAME}/*.c" "${DEMO_NAME}/*.cpp")
    add_executable (${DEMO_NAME} ${HDRS} ${SRCS})
    target_link_libraries (${DEMO_NAME} uv)
    set_target_properties(${DEMO_NAME} PROPERTIES FOLDER "Demos")
endfunction (add_demo)

macro (get_demo_names return_list)
    file (GLOB_RECURSE new_list *.h *.c *.cpp)
    set (dir_list "")
    foreach (file_path ${new_list})
        get_filename_component (dir_path ${file_path} PATH)
        get_filename_component (dir_path ${dir_path} NAME)
        set (dir_list ${dir_list} ${dir_path})
    endforeach ()
    list (REMOVE_DUPLICATES dir_list)
    list (SORT dir_list)
    set (${return_list} ${dir_list})
ENDMACRO()
